{"uuid": "27287d41-c32d-4708-96e6-581c22840d88", "children": ["49b14992-3977-4686-9a9b-8be9537c82ed", "b006c723-bf9f-455f-94c1-5d445e9e0f33"], "befores": [{"name": "test_setup", "status": "passed", "start": 1573118144510, "stop": 1573118154137}], "afters": [{"name": "test_setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=78.0.3904.70)\n  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.18362 x86_64)\n\n", "trace": "  File \"C:\\Users\\manjunathk\\PycharmProjects\\Autoframework_1\\AutomatioFramework\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\manjunathk\\PycharmProjects\\Autoframework_1\\AutomatioFramework\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\manjunathk\\PycharmProjects\\AutomatioFramework\\conftest.py\", line 20, in test_setup\n    driver.close()\n  File \"C:\\Users\\manjunathk\\PycharmProjects\\Autoframework_1\\AutomatioFramework\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\manjunathk\\PycharmProjects\\Autoframework_1\\AutomatioFramework\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\manjunathk\\PycharmProjects\\Autoframework_1\\AutomatioFramework\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1573118217906, "stop": 1573118218337}], "start": 1573118144510, "stop": 1573118218337}